export const APP_ID = "cb27c86043090ca805bbffaedfb9eaa8";
export const UNITS = "metric";
export const LANG = "es";
export const BASE_URL = "https://api.openweathermap.org/data/2.5/";
export const WEATHER_ENDPOINT = "weather";
export const ONECALL_ENDPOINT = "onecall";
export const INTERNAL_ERROR = "No se encontraron resultados.";
export const NOT_DATA = "No se encontraron resultados.";
export const EMPTY_FIELD = "El campo ciudad es requerido.";
